# values.yaml for LGTM Helm Chart

# Grafana configuration
grafana:
  enabled: true
  image:
    repository: grafana/grafana
    tag: ""
  # Administrator credentials when not using an existing secret (see below)
  adminUser: admin
  adminPassword: admin

# Loki configuration
loki-stack:
  enabled: true
  loki:
    enabled: true
    image:
      repository: grafana/loki
      tag: 2.8.1

  promtail:
    enabled: false

  fluent-bit:
    enabled: false

  grafana:
    enabled: false

  prometheus:
    enabled: false

  filebeat:
    enabled: false

  logstash:
    enabled: false
    image: grafana/logstash-output-loki
    imageTag: 1.0.1

# Tempo configuration
tempo:
  enabled: true
  tempo:
    repository: grafana/tempo
    tag: ""
  server:
    http_listen_port: 3100   # HTTP server listen port
  storage:
    trace:
      # tempo storage backend
      # refer https://grafana.com/docs/tempo/latest/configuration/
      ## Use minio s3 for example
      backend: s3
      # store traces in s3
      s3:
        bucket: tempo                                   # store traces in this bucket
        endpoint: s3.dualstack.us-east-2.amazonaws.com  # api endpoint
        # access_key: ...                                 # optional. access key when using static credentials.
        # secret_key: ...                                 # optional. secret key when using static credentials.
        insecure: true                                 # optional. enable if endpoint is http
    

# Mimir configuration
mimir:
  enabled: true
  image:
    repository: grafana/mimir
    # Overrides the image tag whose default is the chart appVersion.
    tag: "2.11.0"

# # Minio configuration
minio:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/minio
    tag: 2024.3.15-debian-12-r0
  mode: standalone
  auth:
    rootUser: admin
    rootPassword: supersecret
  defaultBuckets: "loki, mimir, tempo"