# values.yaml for LGTM Helm Chart

# Grafana configuration
grafana:
  enabled: true
  image:
    repository: grafana/grafana
    tag: ""
  # Administrator credentials when not using an existing secret (see below)
  adminUser: admin
  adminPassword: admin

# Loki configuration
loki-stack:
  enabled: true
  loki:
    enabled: true
    image:
      repository: grafana/loki
      tag: 2.8.1

  promtail:
    enabled: true

  fluent-bit:
    enabled: false

  grafana:
    enabled: false

  prometheus:
    enabled: false

  filebeat:
    enabled: false

  logstash:
    enabled: false
    image: grafana/logstash-output-loki
    imageTag: 1.0.1

# Tempo configuration
tempo:
  enabled: true
  tempo:
    repository: grafana/tempo
    tag: ""
  server:
    http_listen_port: 3100   # -- HTTP server listen port
    

# Mimir configuration
mimir:
  enabled: true
  image: grafana/mimir
  tag: latest
  port: 3300
